### ISSUE TITLE
Possible to do a eventsub-subscription?

### ISSUE THREAD

**Issue by adriel** [twitchdev/twitch-cli#109]
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelupdate

There is some documentation, but I'm struggling to understand how to setup a channel.update subscription to my callback URL using this twitch-cli.

I can get broadcaster details as a one time thing `twitch api get channels -q broadcaster_id=9679595` , but to get it to happen automatically via the callback url, I'm not sure.

Is there somewhere with examples of how I should translate the dev.twitch.tv api page into something that'll work with this cli command.
I'm trying to migrate my old WebSub code to use this cli, but a bit lost. Any push in the right direction would be greatly appreciated.

**Comment by BarryCarlyon** [comment]
The CLI is just a test tool to send an example payload to your EventSub Callback.

So you don't have to use the dashboard/live Twitch to Trigger a "Channel update"

Essentailly the migration from WebSub to EventSub is straightforward:

- Challenges are over POST now instead of GET
- The Signature is calculated slightly differently.
- The payloads are a different format

Depending on your language of choice, I have a node and a PHP example over at https://github.com/BarryCarlyon/twitch_misc/tree/main/eventsub/handlers

And you can use the CLI to punt test messages at your callback based on my code.

So the CLI just does the same thing as the live website does. It's just easier to spam a CLI command than to ask the live system to do send a payload. (and lets you test parsing subscriber data without needing an affiliate or partner or to spend money to trigger an event)

**Comment by adriel** [comment]
ooh, that would certainly explain my struggle to find the documentation for it. Updated my old code from WebSub to EventSub and seems to be working now. Will have to give this cli a try to send some dummy events through.

Thank you for the clear and thorough reply.
