### ISSUE TITLE
Docs for mock data generation give incorrect counts

### ISSUE THREAD

**Issue by tomihawk** [twitchdev/twitch-cli#196]
The documentation at https://dev.twitch.tv/docs/cli/mock-api-command and https://github.com/twitchdev/twitch-cli/blob/main/docs/mock-api.md states that the `twitch mock-api generate` command will default to generate 10 users but it seems to default to 1.  The first link also says that if you run `twitch mock-api start` without having generated any data it will generate the default 10, but it seems to generate 25 users.

The 25 users seems to come from https://github.com/twitchdev/twitch-cli/blob/fca40a4aec6ecc125a9560c3e50a6f5b3756c919/internal/mock_api/mock_server/server.go#L41 or https://github.com/twitchdev/twitch-cli/blob/fca40a4aec6ecc125a9560c3e50a6f5b3756c919/internal/events/mock_wss_server/server.go#L352

I'm guessing the 1 comes from the &count variable being referenced at https://github.com/twitchdev/twitch-cli/blob/fca40a4aec6ecc125a9560c3e50a6f5b3756c919/cmd/api.go#L103 is not defined anywhere.  I'm not a Go programmer so I'm not sure why the compiler would let you reference the memory address of an undefined variable but specifying a number with `-c` works fine.

**Comment by Xemdo** [comment]
Will update the docs to reflect the 25 default.

For it generating 1 instead of 10, this is because the count variable is referenced twice. First is here:, as you mentioned https://github.com/twitchdev/twitch-cli/blob/fca40a4aec6ecc125a9560c3e50a6f5b3756c919/cmd/api.go#L103
And again at https://github.com/twitchdev/twitch-cli/blob/fca40a4aec6ecc125a9560c3e50a6f5b3756c919/cmd/events.go#L114
The one in events.go must be executed second, because it overrides. I'll split these variables up to avoid any issues.
