### ISSUE TITLE
Signature calculation

### ISSUE THREAD

**Issue by fabian-bickel** [twitchdev/twitch-cli#34]
https://github.com/twitchdev/twitch-cli/blob/e0cd933ce4764e8bd9f6924528d950373ab6199a/internal/events/trigger/forward_event.go#L107

I use https://d-fischer.github.io/versions/4.4/twitch-eventsub/
The twitch-eventsub module verifies the signature  and real events are working and the mock events are not working because it can not verify the signature.

**Comment by lleadbet** [comment]
Hey there! 

Can you explain further what you're seeing here?

**Comment by fabian-bickel** [comment]
I think the signature calculation from real events is different to the implementation in this cli.

**Comment by lleadbet** [comment]
What version are you running of the CLI- v0.3.3?

**Comment by fabian-bickel** [comment]
Yeah 0.3.3

**Comment by lleadbet** [comment]
Got it. 

I'm having a hard time replicating this here; Can you provide an example secret you're using (doesn't actually need to be the real one) and the CLI command you're using?

**Comment by fabian-bickel** [comment]
secret: thisShouldBeARandomlyGeneratedFixedString

twitch event trigger follow -f 31239503  -s thisShouldBeARandomlyGeneratedFixedString -F https://<servername>/channel.follow.31239503

channel.follow.31239503 i need this path because the module generates the path

**Comment by lleadbet** [comment]
@fabian-bickel - 

I actually dug into this because this is very odd and seems isolated to this specific library- other libraries do not have this issue. 

The tldr is that the secret you pass to the `twitch` library is prepended with the ID of the subscription. Meaning, for example, channel subscription events would need to be:

`channel.subscribe.<user_id>.<passed_secret>`

Then through the CLI, you can trigger them via: 

```
twitch event trigger subscribe -t 44635596 -F http://localhost:8000/channel.subscribe.44635596 -s channel.subscribe.44635596.test
```

(using my userID). 

This is defined here in the library's source: https://github.com/d-fischer/twitch/blob/main/packages/twitch-eventsub/src/Subscriptions/EventSubSubscription.ts#L31

Feel free to raise this to the library owner as a documentation update, since the signing aspect seems to work with this specific part sorted. Appreciate the flag regardless; good to know.

**Comment by fabian-bickel** [comment]
Thanks for you help :)
