### ISSUE TITLE
Allow flag to set game ID and title

### ISSUE THREAD

**Issue by rohanrichards** [twitchdev/twitch-cli#60]
https://github.com/twitchdev/twitch-cli/blob/80f8da3e57cf4945b19388bf571c9fa36b82793c/internal/events/types/stream_change/stream_change_event.go#L83-L84

It would be helpful if we could pass in the Game ID and title on stream change updates. E.g

`twitchevent trigger stream-change -F http://localhost:3000 -G "Path of Exile"`

**Comment by lleadbet** [comment]
I think the concern here is that we can allow you to set both manually, but using a random name (such as `Path of Exile`) requires a lookup via API, thus means you need to configure it properly beforehand. 

I'm not entirely opposed to the idea, however it is a fairly unique edgecase. 

If you're okay with only setting one or the other (or both) manually, I can certainly hook up existing triggers since they're already there (`item-id` and `status` can be reused for this).
